sudo: true
os: osx
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-osx.pkg
  global:
    secure: NuiQn6FT+HoXu+agALqXpCLNrWRSnu9dgAn/gLHaGNIxmTD3ZtXbAne4JMCuNzWy5BDm9/QdaC0yqjcC64htB9eFBMHB16D5sL2hszLpJkIMnBSC8w1pUgwf2JCln42Zl4YO2t34tmqJRAwcQoCmEu53ydSvta3afL67J4ARu7jXIK/uWlK5DJIIDhtZvYakmPsWfkowRplP5BYbks3IAYWSZZ+1iB9ozkVpON+w6ZFNBWluBM93AdYqBDjv/NVFzFSm/4hIWDbgdVkLk5bGnnpU343yG8tZMUCHPW796lNIif2XkPszddTw109egEEl7KyYxI3uKGDjsU6m8fJ/bsspShsKsR/jZRlZ7VB4xyrJqvi4qrHdDssIuLzbAssaOpOpaZx7k6JgdYXW8j01ikVpfxoaDrPeETBubBVhFClSbDgYwZvcLq5Kpft0jrVHJ68fi1+m19SklGT6evnI/yB6XcuLvz+bBL+ggnoIq0l+zsUrRe1Op5TRziZReBSdgihh0JlY7p/53aan0vW/arM+p/3qC9oAy2p+d/ozq0eCwv2+SDnSl0FoqDWuKRN2qMLrGP5jYlZJOGZniV2TinW2PgziubMxSpqU4yOwzQmm2L05hrO3dMw+gLOudsJp40i6CrDFODhDKDCv4ZU9By69Prcuo4X3acUxjEvRCAs=
before_install:
- openssl aes-256-cbc -k $SERVER_KEY_PASS -in assets/server.key.enc -out assets/server.key
  -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- curl $URL --output sfdx-osx.pkg
- sudo installer -pkg sfdx-osx.pkg -target /
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key
  --username $DEVHUB_USERNAME --setdefaultdevhubusername -a huborg
script:
- sfdx force:org:create -v huborg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human -w 10
- sfdx force:org:delete -u ciorg -p
